package frc.robot;

import static edu.wpi.first.units.Units.*;
import java.util.Dictionary;
import java.util.Hashtable;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

import frc.robot.subsystems.Swerve;
import frc.lib.util.COTSTalonFXSwerveConstants;

import com.pathplanner.lib.util.FlippingUtil;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.wpilibj.DriverStation;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {
        public final class OperatorConstants{
    public static final COTSTalonFXSwerveConstants CHOSEN_MODULE = COTSTalonFXSwerveConstants.SDS.MK4i
            .Falcon500(COTSTalonFXSwerveConstants.SDS.MK4i.driveRatios.L2);
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with
    // the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
            .withKP(100).withKI(0).withKD(0.5)       // stiff angle hold (kP=MK4i default) + kD damping for smoothness
            .withKS(0.13).withKV(2.38).withKA(0.03)  // from SysId 2026-06-19; azimuth (mechanism) units
            .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains = new Slot0Configs()
            .withKP(0.10).withKI(0).withKD(0)        // velocity loop: kS/kV feedforward does the work, kP trims error (smooth)
             .withKS(0.17).withKV(0.11).withKA(0.0);  // kA=0 is safe for swerve velocity control

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

    // The Supply current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(20.0);

    // Initial configs for the drive and steer motors and the azimuth encoder; these
    // cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API
    // documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration()
            .withCurrentLimits(
                    new CurrentLimitsConfigs()
                            // Prevent excessive drive Supply current and help avoid brownouts.
                            .withSupplyCurrentLimit(Amps.of(30))
                            .withSupplyCurrentLimitEnable(true));
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
            .withCurrentLimits(
                    new CurrentLimitsConfigs()
                            // Swerve azimuth does not require much torque output, so we can set a
                            // relatively low
                            // Supply current limit to help avoid brownouts without impacting performance.
                            .withSupplyCurrentLimit(Amps.of(30))
                            .withSupplyCurrentLimitEnable(true));
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus kCANBus = new CANBus("", "./logs/example.hoot");

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
//     public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(3.14 / 8);

    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(0.675);

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    private static final double kCoupleRatio = 3.5714285714285716;

    private static final double kDriveGearRatio = 6.746031746031747;
    private static final double kSteerGearRatio = 21.428571428571427;
    private static final Distance kWheelRadius = Meters.of(CHOSEN_MODULE.wheelDiameter / 2);

    private static final boolean kInvertLeftSide = false;
    private static final boolean kInvertRightSide = true;

    private static final int kPigeonId = 8;

    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);

   
    private static final boolean kFrontLeftSteerMotorInverted = true;
    private static final boolean kFrontLeftEncoderInverted = false;

    private static final Distance kFrontLeftXPos = Inches.of(12.5);
    private static final Distance kFrontLeftYPos = Inches.of(12.5);

   
    private static final boolean kFrontRightSteerMotorInverted = true;
    private static final boolean kFrontRightEncoderInverted = false;

    private static final Distance kFrontRightXPos = Inches.of(12.5);
    private static final Distance kFrontRightYPos = Inches.of(-12.5);

    
    private static final boolean kBackLeftSteerMotorInverted = true;
    private static final boolean kBackLeftEncoderInverted = false;

    private static final Distance kBackLeftXPos = Inches.of(-12.5);
    private static final Distance kBackLeftYPos = Inches.of(12.5);
    // Swerve Motor IDs

    // Front Left
    private static final int kFrontLeftDriveMotorId = 4;
    private static final int kFrontLeftSteerMotorId = 9;
    private static final int kFrontLeftEncoderId = 31;
    private static final Angle kFrontLeftEncoderOffset = Rotations.of(0.312744140625 + 6.28 + 3.14 + 0.0374+0.025 + (3.14/10)+(3.14/10)+(3.14/10));

    // Front Right 
    private static final int kFrontRightDriveMotorId = 12;
    private static final int kFrontRightSteerMotorId = 11;
    private static final int kFrontRightEncoderId = 5;
    private static final Angle kFrontRightEncoderOffset = Rotations
            .of(-0.02685546875 + (3.14 / 2) + (3.14 / 4) - 6.28 - 3.14 + 0.0276 -(3.14/2/2)+(3.14/12)+(3.14/4)+0.025 + (3.14/10)+(3.14/10)+(3.14/10)+(3.14/200));
    // Back Right
    private static final int kBackRightDriveMotorId = 14;
    private static final int kBackRightSteerMotorId = 13;
    private static final int kBackRightEncoderId = 10;
    private static final Angle kBackRightEncoderOffset = Rotations.of(0.228759765625 + 0.5 + 0.025 + (3.14/10)+(3.14/10)+(3.14/10));

    // Back Left
    private static final int kBackLeftDriveMotorId = 7;
    private static final int kBackLeftSteerMotorId = 6;
    private static final int kBackLeftEncoderId = 1;
    private static final Angle kBackLeftEncoderOffset = Rotations.of(0.18310546875+(3.14/4)-(3.14/8)+3.14+6.28+(3.14/12)+(3.14/4)-(3.14/400));

    
    private static final boolean kBackRightSteerMotorInverted = true;
    private static final boolean kBackRightEncoderInverted = false;

    private static final Distance kBackRightXPos = Inches.of(-12.5);
    private static final Distance kBackRightYPos = Inches.of(-12.5);

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft = ConstantCreator
            .createModuleConstants(
                    kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId, kFrontLeftEncoderOffset,
                    kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted,
                    kFrontLeftEncoderInverted);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight = ConstantCreator
            .createModuleConstants(
                    kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId, kFrontRightEncoderOffset,
                    kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted,
                    kFrontRightEncoderInverted);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft = ConstantCreator
            .createModuleConstants(
                    kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId, kBackLeftEncoderOffset,
                    kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted,
                    kBackLeftEncoderInverted);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight = ConstantCreator
            .createModuleConstants(
                    kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId, kBackRightEncoderOffset,
                    kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted,
                    kBackRightEncoderInverted);

    /**
     * Creates a CommandSwerveDrivetrain instance.
     * This should only be called once in your robot program,.
     */
    public static Swerve createDrivetrain() {
        return new Swerve(
                DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight);
    }

    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected
     * device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct
         * the devices themselves. If they need the devices, they can access them
         * through
         * getters in the classes.
         *
         * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
         * @param modules             Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, modules);
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct
         * the devices themselves. If they need the devices, they can access them
         * through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                double odometryUpdateFrequency,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, odometryUpdateFrequency, modules);
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct
         * the devices themselves. If they need the devices, they can access them
         * through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve
         *                                  drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz
         *                                  on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry
         *                                  calculation
         *                                  in the form [x, y, theta]ᵀ, with units in
         *                                  meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision
         *                                  calculation
         *                                  in the form [x, y, theta]ᵀ, with units in
         *                                  meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                double odometryUpdateFrequency,
                Matrix<N3, N1> odometryStandardDeviation,
                Matrix<N3, N1> visionStandardDeviation,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, odometryUpdateFrequency,
                    odometryStandardDeviation, visionStandardDeviation, modules);
                }
                }
        }

        public static final int AXIS_X = 0; // X-axis 
        public static final int AXIS_Y = 1; // Y-axis 
        public static final int AXIS_TWIST = 2; // rotation

        public static final int operatorPort = 1;
        public static final int driverPort = 0;
        public static final int progJoystickPort = 2;
        public static final int progOpJoystickPort = 3;


        public static final int resetGyroPort = 10; 
        public static final int slowModePort = 6;

        public final class IntakeConstants {
                // Square = 1
                // X=2
                // Circle = 3
                // Triangle = 4
                // LB = 5
                // RB = 6
                // ZL = 7
                // ZR = 8
                // Left niche = 9
                // Right niche = 10
                // L3 = 11
                // R3 = 12
                // Big button = 14

                public final static int intakeID = 18;
                public final static double intakeSpeed = -0.6;
                public final static int intakePort = 2;
                public final static double IntakeCurrentlimit = 20;
        }
        public final class ControllerConstants {
                public final static int square = 1;
                public final static int x = 2;
                public final static int circle = 3;
                public final static int triangle = 4;
                public final static int LB = 5;
                public final static int RB = 6;
                public final static int ZL = 7;
                public final static int ZR = 8;
                public final static int leftNiche = 9;
                public final static int rightNiche = 10;
                public final static int L3 = 11;
                public final static int R3 = 12;
                public final static int bigButton = 14;
        }
        public final class TurretConstants {    
                public final static int swivelLimitPort = 1;
                public final static int hoodID = 16;
                public final static int swivelID = 0;

                public final static double swivelP = 20;
                public final static double swivelI = 0.01;
                public final static double swivelD = 0.01;
                public final static double swivelAccel = 20; //ai says to reduce the accel even more like down to 20-30 to maybe improve shoot on move 
                public final static double swivelVel = 50;
                public final static double swivelStatorLimit = 30;
                public final static double swivelSupplyLimit = 20;

                public static double antiRotationOffset = 0.0;
                public static double antiMultiplier = -0.05;

                public final static double hoodP = 0.07;
                public final static double hoodI = 0.001;
                public final static double hoodD = 0.0005;
                public final static double hoodAccel = 0.2;
                public final static double hoodVel = 0.2;

                public final static double swivelHardLimit2 = -2.5;
                public final static double swivelHardLimit1 = 6.02;
                public final static double swivelDeadMid = (swivelHardLimit2 - 5.8) / 2;

                public final static double hoodHardLimit1 = 2.96;
                public final static double hoodHardLimit2 = 0;

                public final static double swivelSoftLimit2 = -2.33;
                public final static double swivelSoftLimit1 = 5.95;

                public final static double hoodSoftLimit1 = 2.76;
                public final static double hoodSoftLimit2 = 0.1;

                public final static double manualSwivel = 2.92041015625;
                public final static double manualHood = 0.2;

                public final static double hoodGearRatio = 72 / 289;
                public static double swivelGearRatio = ((0.032));

                public static double swivelOffset = 0;

                public static double virtualX = 0;
                public static double virtualY = 0;
                public static double dx = 0;
                public static double dy = 0;
                public static double realdx = 0;
                public static double realdy = 0;



                public final static Dictionary<Integer, Double> areaToAngle = new Hashtable<Integer, Double>();
                public TurretConstants() {
                        areaToAngle.put(0, 0.0);
                        areaToAngle.put(1, 10.0);
                        areaToAngle.put(2, 20.0);
                        areaToAngle.put(3, 30.0);
                        areaToAngle.put(4, 40.0);
                        areaToAngle.put(5, 50.0);
                        areaToAngle.put(6, 60.0);
                        areaToAngle.put(7, 70.0);
                        areaToAngle.put(8, 80.0);
                        areaToAngle.put(9, 90.0);
                }

                public static final double kTurretOffsetX  = -0.133; // X offset (forward +X, backward -X) from robot center to turret (meters) 
                public static final double kTurretOffsetY = 0.0; // Y offset (left +Y, right -Y) from robot center to turret (meters)
                public static final double kTurretOffsetZ = 0.3; // Z offset (up +Z, down -Z) from robot center to turret (meters)

                public static final double kMinAngleDegrees = -200.0;
                public static final double kMaxAngleDegrees = 180.0;

                // Shooting range limits (meters)
                public static final double kMinShootingDistance = 0.5;
          
                public static final double kMaxShootingDistance = 10.0;
                public static boolean running = false;
        }

        public final class StorageConstants {
                public final static int wheelID = 15;
                public final static int indexMotorID = 17;
                public final static int indexMotor2ID = 19;
                public final static int indexLimitPort = 0;

                public final static double attackSpeed = -80;
                public final static double defenseSpeed = -80;
                // Indexer velocity target (units match rotor velocity measurement). Set to 75 (1.5x) by default.
                public final static double indexSpeed = 112.5; // bumped 1.5x from 75
                // Indexer PID/FF defaults for velocity control
                public final static double indexerP = 0.18; // stronger P (1.5x)
                public final static double indexerI = 0.0;
                public final static double indexerD = 0.0;
                public final static double indexerFF = 0.0;
                public final static double wheelFF = 0.12;
                public final static double wheelP = 0.5;
                public final static double wheelI = 0;
                public final static double wheelD = 0;
                 public final static double wheelStatorLimit = 80;
                public final static double wheelSupplyLimit = 45;
                ;
                 public final static double indexerStatorLimit = 30;
                public final static double indexerSupplyLimit = 30;
        }

        public class FieldConstants {
    /** Full length of the FRC field in meters (2026 season) */
    public static final double kFieldLength = 16.5405;

    // SHOOT 3D targets (Blue alliance origin)
    private static final Pose3d hubTargetBlue       = new Pose3d(4.620, 4.040, 3.057144, new Rotation3d());
    private static final Pose3d leftPassTargetBlue  = new Pose3d(2.50, 6.0, 0, new Rotation3d());
    private static final Pose3d rightPassTargetBlue = new Pose3d(2.50, 1.960, 0, new Rotation3d());

    // PATHFIND Pose 2D (Blue alliance origin)
    private static final Pose2d leftTrenchBlue  = new Pose2d(3.650, 7.411, new Rotation2d(Math.PI));
    private static final Pose2d rightTrenchBlue = new Pose2d(3.650, 0.635, new Rotation2d(0));

    private static final Pose2d leftNeutralBlue = new Pose2d(8.2, 7.2, new Rotation2d(-Math.PI / 2));
    private static final Pose2d rightNeutralBlue = new Pose2d(8.2, 0.8, new Rotation2d(Math.PI / 2));

    private static final Pose2d leftOppBlue = new Pose2d(13.4, 7.4, new Rotation2d(0));
    private static final Pose2d rightOppBlue = new Pose2d(13.4, 0.627, new Rotation2d(Math.PI));
    // -------------------------------------------------------------------------
    // Pose2d flip helpers
    // -------------------------------------------------------------------------

    /**
     * Flips a Pose2d to the red alliance side of the field using the same
     * rotational symmetry that PathPlanner uses for 2026:
     *   flipped_X = fieldSizeX - X,  flipped_Y = fieldSizeY - Y
     */
    public static Pose2d flipPose(Pose2d pose) {
        return FlippingUtil.flipFieldPose(pose);
    }

    /**
     * Returns the pose flipped to the red alliance side if currently on red,
     * otherwise returns it unchanged.
     */
    public static Pose2d flipIfRed(Pose2d pose) {
        return isRedAlliance() ? FlippingUtil.flipFieldPose(pose) : pose;
    }

    // -------------------------------------------------------------------------
    // Pose3d flip helpers
    // -------------------------------------------------------------------------

    /**
     * Flips a Pose3d to the red alliance side of the field using the same
     * rotational symmetry that PathPlanner uses for 2026:
     *   flipped_X = fieldSizeX - X,  flipped_Y = fieldSizeY - Y,  yaw += 180°
     */
    public static Pose3d flipPose3d(Pose3d pose) {
        Rotation3d flipped = new Rotation3d(
            pose.getRotation().getX(),
            pose.getRotation().getY(),
            pose.getRotation().getZ() + Math.PI
        );
        return new Pose3d(
            new Translation3d(
                FlippingUtil.fieldSizeX - pose.getX(),
                FlippingUtil.fieldSizeY - pose.getY(),
                pose.getZ()),
            flipped
        );
    }

    /**
     * Returns the Pose3d flipped to the red alliance side if currently on red,
     * otherwise returns it unchanged.
     */
    public static Pose3d flipIfRed(Pose3d pose) {
        return isRedAlliance() ? flipPose3d(pose) : pose;
    }

    // -------------------------------------------------------------------------
    // Alliance helper
    // -------------------------------------------------------------------------

    /** Returns true if the robot is currently on the red alliance. */
    public static boolean isRedAlliance() {
        return DriverStation.getAlliance()
            .orElse(DriverStation.Alliance.Blue) == DriverStation.Alliance.Red;
    }

    // -------------------------------------------------------------------------
    // Pose getters (automatically flipped for red alliance)
    // -------------------------------------------------------------------------

    /** Hub (high goal) 3D target pose, automatically flipped for red alliance. */
    public static Pose3d getHubTarget() {
        return flipIfRed(hubTargetBlue);
    }

    /** Left pass 3D target pose, automatically flipped for red alliance. */
    public static Pose3d getLeftPassTarget() {
        return flipIfRed(leftPassTargetBlue);
    }

    /** Right pass 3D target pose, automatically flipped for red alliance. */
    public static Pose3d getRightPassTarget() {
        return flipIfRed(rightPassTargetBlue);
    }

    /** Left trench shoot pose, automatically flipped for red alliance. */
    public static Pose2d getLeftTrenchShoot() {
        return flipIfRed(leftTrenchBlue);
    }

    /** Right trench shoot pose, automatically flipped for red alliance. */
    public static Pose2d getRightTrenchShoot() {
        return flipIfRed(rightTrenchBlue);
    }

    /** Left neutral-zone pose, automatically flipped for red alliance. */
    public static Pose2d getLeftNeutral() {
        return flipIfRed(leftNeutralBlue);
    }

    /** Right neutral-zone pose, automatically flipped for red alliance. */
    public static Pose2d getRightNeutral() {
        return flipIfRed(rightNeutralBlue);
    }

    /** Left opponent-zone pose, automatically flipped for red alliance. */
    public static Pose2d getLeftOpp() {
        return flipIfRed(leftOppBlue);
    }

    /** Right opponent-zone pose, automatically flipped for red alliance. */
    public static Pose2d getRightOpp() {
        return flipIfRed(rightOppBlue);
    }
    }
}



